name: databricks-support-app
command:
  - "sh"
  - "-c"
  - "chmod +x ./support-app && ./support-app"

env:
  - name: DB_HOST
    valueFrom: db_host
  - name: DB_PORT
    valueFrom: db_port
  - name: DB_USER
    valueFrom: db_user
  - name: DB_NAME
    valueFrom: db_name
  - name: DB_PASSWORD
    valueFrom: db_password
  - name: DB_SSLMODE
    value: "require"